language: elixir
elixir:
  - 1.6.0
  - 1.7.0
  - 1.8.0
  - 1.9.0
services:
  - postgresql
env:
  - MIX_ENV=test
script:
  - mix deps.get
  - mix compile
  - mix ecto.setup
  - mix credo
  - mix coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)